### ISSUE TITLE
InputFile does not reflect the Telegram API

### ISSUE THREAD

**Issue by KnorpelSenf** [KnorpelSenf/typegram#11]
The `interface InputFile` is a union of a number of other interfaces. However, these interfaces do not appear in the documentation at all, and neither do they describe object structures that are supported by Telegram this way.

The reason for this oddity is that it resembles a part of the `telegraf` library, but even this is not done properly: `InputFileByURL.filename` is for instance not a required property.

It is therefore necessary to remove the faulty types from `typegram` and make it accurately reflect the Telegram Bot API again. If other libraries like `telegraf` want to wrap certain API methods with their own argument structures, it makes sense to add the type annotations there.

**Comment by wojpawlik** [comment]
How about deprecating `InputFile`, and adding optional `InputFile` type parameter to `Telegram`, `TelegramP` and `Opts` for easy customization?

**Comment by KnorpelSenf** [comment]
Nah that's not an option. An `InputFile` is not just “another way to use the Telegram API”, so it doesn't make sense semantically. Also, this would trickle down to the `InputMedia*` types, and then we'd get all of those problems with incompatible methods and types, contravariant positions, etc as we already have in `telegraf`. (Remember that it should definitely possible to add a generic version in dependent libraries if that is desired.)

It is possible to do this via inheritance. It is also possible to do this via union types. We could also make only certain methods (optionally) generic. Maybe there are even more alternatives, I'm not yet sure what the cleanest solution would be.

This library should try to reflect the Telegram API and provide useful types. Even though its most popular consumer is `telegraf`, it is can be on its own (I have systems running in production that use it but not `telegraf`). So strictly speaking, at this point, given that we have no idea about what other types an `InputFile` can be, `string` would be the most accurate alias for `InputFile`, but hopefully we can do better.

**Comment by wojpawlik** [comment]
> We could also make only certain methods (optionally) generic.

Bad idea. Would make it difficult if not impossible to `implements TelegramP`.

> An `InputFile` is not just “another way to use the Telegram API”, so it doesn't make sense semantically.

But it is just another way of mapping JS object property to `multipart/form-data`.

> Also, this would trickle down to the `InputMedia*` types

Those should be deprecated as well.

> we'd get all of those problems with incompatible methods and types

Methods would be incompatible only if they use incompatible `InputFile`. Won't happen if library sticks to one definition.

**Comment by KnorpelSenf** [comment]
@wojpawlik You have valid points. I experimented a bit around and concluded eventually that none of the options is really nice.

> > Also, this would trickle down to the `InputMedia*` types
> 
> Those should be deprecated as well.

I believe these types are useful and they should stay, were you perhaps talking about the `InputFile*` types? I agree that those no longer belong in the library.

---

What I disliked the most about making the `interface Telegram` generic is that it would require discipline from the library consumer. The type variable has to be included whenever affected `typegram` types would be specified, and it always had to be the same variable for `Telegram`, `TelegramP`, `Opts`, and all `InputMedia*` types, otherwise you'd run into errors that are really difficult to spot. (I was actually already bothered by this when I was just playing around with the generic version during my experiments.)

Fortunately, it is possible to remedy the problem by introducing something I would call a Proxy Type. It is named `Typegram` and basically transforms the complete library such that the same adjusted `InputFile` type is used in all places. We can now use a type parameter in one single place and obtain a wealth of synchronously customized types.

It does indeed feel overly complicated to _write_ the declarations like this, but it was definitely by far the nicest way to _use_ `typegram`.

Please check out #13 and confirm that the change of the `media` property for the `InputMedia*` types matches your expectation.
