### ISSUE TITLE
The `proximity_alert_triggered` is required for `ProximityAlertTriggered` message

### ISSUE THREAD

**Issue by sdcdsvsdv423** [KnorpelSenf/typegram#19]
Now parameter `proximity_alert_triggered` is optional.

https://github.com/KnorpelSenf/typegram/blob/master/message.d.ts#L178

Because of this, it is not possible to exclude `ProximityAlertTriggeredMessage` from the union `Message` type. It will always be `never`.

<img width="674" alt="Screenshot 2021-01-23 at 13 16 58" src="https://user-images.githubusercontent.com/5320711/105569573-8e063a00-5d7d-11eb-9887-511f36e300cd.png">

**Comment by KnorpelSenf** [comment]
Thanks. Will take care of it later today.
