### ISSUE TITLE
Distinguish between types and return types

### ISSUE THREAD

**Issue by KnorpelSenf** [KnorpelSenf/typegram#2]
Some properties are "returned only in `getChat`" or "...`getMe`". They should be moved from the base interfaces and put only in the return value they're present in.

Example:
```js
interface User { /* ... */ } // e.g. used in interface ChatMember
interface GottenUser extends User { /* ... */ } // used exclusively in getMe
```

**Comment by wojpawlik** [comment]
I don't like the `GottenUser` name, how about `User_getMe` and `Chat_getChat`?

Also, how about adding `is_bot: True` to `User_getMe`?

**Comment by KnorpelSenf** [comment]
I agree that GottenUser is weird, but let's stay with CamelCasing.

> Also, how about adding `is_bot: True` to `User_getMe`?

That sounds good
