### ISSUE TITLE
Chat Interface does not appear in vscode autocomplete

### ISSUE THREAD

**Issue by mehdikhody** [KnorpelSenf/typegram#24]
Hi, Thanks for your astonishing work. I, myself created a similar project but when I saw this repository, I chose to stick with this.
But there is a small issue that I have with it:

![code api test](https://user-images.githubusercontent.com/22590626/111700896-4a94ed00-884f-11eb-8e35-cc706d4a5c6f.jpg)

There is only 2 options in vscode autocomplete dropdown list but actual result is different.
```json
...
"chat": {
  "id": 219759038,
  "first_name": "Mehdi",
  "last_name": "Khody",
  "username": "MehdiKhody",
  "type": "private"
},
...
```

In `API.ts`, method `sendMessage` is look like this:
```ts
import { ReadStream } from "fs"
import { Typegram } from "typegram"

type Telegram = Typegram<ReadStream>
type Methods = Telegram["Telegram"]
type Params<M extends keyof Methods> = Parameters<Methods[M]>[0]
type Response<M extends keyof Methods> = ReturnType<Methods[M]>


async sendMessage(props: Params<"sendMessage">): Promise<Response<"sendMessage">> {
    return this.send("sendMessage", props)
}
```

Is there any solution for this problem?

**Comment by mehdikhody** [comment]
I solved it with this:
```ts
if (response.chat.type === "private") {
  console.log(response.chat.username)
}
```

**Comment by KnorpelSenf** [comment]
Nice, that's the correct way to do it because there are different interfaces for each type of chat, and you correctly narrow down the union type now.

Friendly reminder to revoke the above bot token :)

**Comment by mehdikhody** [comment]
Thanks for reply and dont worry, its a fake token.
