### ISSUE TITLE
Missing import of CommonMessageBundle [v3.5.0]

### ISSUE THREAD

**Issue by florian-g-** [KnorpelSenf/typegram#29]
Thank you for providing this repo! I was not allowed to quickly provide a PR so I open this issue.

Problem:
In v3.5.0 the update.d.ts is missing an import of CommonMessageBundle from message.d.ts

Fix:
import { CommonMessageBundle, Message, Poll, PollAnswer } from "./message";

**Comment by KnorpelSenf** [comment]
That's probably due to the backporting. All changes are cherry-picked from another repo, so sometimes things go wrong.

I don't know why you can't PR from a fork of this repo, but I can just fix it myself in the coming days.

**Comment by BusinessDuck** [comment]
> That's probably due to the backporting. All changes are cherry-picked from another repo, so sometimes things go wrong.
> 
> I don't know why you can't PR from a fork of this repo, but I can just fix it myself in the coming days.

May be this regarding with git merge strategy

**Comment by EdJoPaTo** [comment]
@florian-g- Currently it doesnt look like you have a fork currently: https://github.com/KnorpelSenf/typegram/network/members

Did you try to push changes to a branch of this repo which isnt possible as you dont have permissions to do so? Pushing to a fork will provide banners on GitHub which basically say "do you want to create a PR for this branch?"

**Comment by florian-g-** [comment]
@EdJoPaTo I didn't fork, just created a feature branch and tried to push it to this repo.

I ran into the issue itself because of telegraf's dependency to typegram. But if I got it right, migrating grammY seems to be preferred anyway.

Thanks to all for your quick reply! :+1:

**Comment by KnorpelSenf** [comment]
People don't have permission to modify the code in arbitrary repositories of someone else. Contributions always work via fork+PR (unless you know them and you explicitly grant them push permission).

Going to fix this now

**Comment by KnorpelSenf** [comment]
Fixed in https://github.com/KnorpelSenf/typegram/commit/2c94c5c62d314cbba56c8c1f9c204d72313ac409
