### ISSUE TITLE
Audio message not extending MediaMessage

### ISSUE THREAD

**Issue by ciricc** [KnorpelSenf/typegram#30]
Telegram supports audio media group messages, but telegraf type doesn't.

```ts
bot.on("channel_post", (ctx) => {
    if ("media_group_id" in ctx.channelPost) {
        if ("audio" in ctx.channelPost) {
            console.log(ctx.channelPost) // never type
        }
    }
})
```

**Comment by KnorpelSenf** [comment]
I assume this applies to document messages likewise. Can you confirm this?

Both message types should extend media messages rather than captionable messages. This mistake was made when Telegram started to allow more message types in albums.

**Comment by ciricc** [comment]
I mean audio file media group message

![image](https://user-images.githubusercontent.com/20687373/147416081-9deb64e9-925b-4992-b572-c2725d657c77.png)

It looks like this

![image](https://user-images.githubusercontent.com/20687373/147416097-903c4dd7-c4d5-4ecf-813b-e9cb92de9fda.png)

Or with caption like this 

![image](https://user-images.githubusercontent.com/20687373/147416390-cf8ed20f-531a-4c24-9023-e3d1f4c9304a.png)

https://core.telegram.org/bots/api#inputmediaaudio

**Comment by KnorpelSenf** [comment]
I understood that. The question is if you have the same problem with document messages, such as PDF files. I believe those messages are affected by the same bug. Can you confirm this?

**Comment by EdJoPaTo** [comment]
the API states Audio, Document, Photo and Video should work there.
https://core.telegram.org/bots/api#sendmediagroup

Interestingly `InputMediaAnimation` also exists as a possible `InputMedia` but looks like it isnt working for `sendMediaGroup`.

**Comment by KnorpelSenf** [comment]
That's correct. `InputMedia` is also used in https://core.telegram.org/bots/api#editmessagemedia and that's where you can specify `InputMediaAnimation`.

**Comment by ciricc** [comment]
Sorry, i didn't understand. Yes, this bug reproduces also with documents. Documents also can be sent in media group.

**Comment by KnorpelSenf** [comment]
Alrighty, then I know how to fix this. Thanks for testing it. Will push a patch release tomorrow.
