### ISSUE TITLE
Typescript — TS2308: Module "./default" has already exported a member named 'Ret'

### ISSUE THREAD

**Issue by dilyanpalauzov** [KnorpelSenf/typegram#41]
Typescript 4.9.3 reports:
```
node_modules/typegram/index.d.ts:10:1 - error TS2308: Module "./default" has already exported a member named 'Ret'. Consider explicitly re-exporting to resolve the ambiguity.

10 export * from "./proxied";
   ~~~~~~~~~~~~~~~~~~~~~~~~~~
Errors  Files
     1  node_modules/typegram/index.d.ts:10
```

**Comment by dilyanpalauzov** [comment]
I am using typegram@4.1.0.

**Comment by StasPonomaryov** [comment]
The same issue on Typescript 4.5.4

**Comment by KnorpelSenf** [comment]
It looks like TS does not care about which type definitions are exported and which ones are local to the module. That's why there is a clash.

Please check if #42 is the answer to this problem.

**Comment by dilyanpalauzov** [comment]
> Please check if https://github.com/KnorpelSenf/typegram/pull/42 is the answer to this problem.

Yes, it is.
