### ISSUE TITLE
Build typescript project error with "typegram" module

### ISSUE THREAD

**Issue by doanthuanthanh88** [KnorpelSenf/typegram#43]
### Description
I've got the below error message when build the project

node_modules/typegram/index.d.ts:10:1 - error TS2308: Module "./default" has already exported a member named 'Ret'. Consider explicitly re-exporting to resolve the ambiguity.

### Environment information
- node: v18.12.1
- typescript: Version 4.9.3

**Comment by KnorpelSenf** [comment]
This was already fixed and it will be released soon, no ETA. In the meantime, consider installing from source.
