### ISSUE TITLE
Perhabs telegram has been changed types for ReplyMarkup

### ISSUE THREAD

**Issue by a-badalyan** [KnorpelSenf/typegram#47]
Perhabs telegram has been changed types for ReplyMarkup

Link to official documentation - https://core.telegram.org/type/ReplyMarkup

ReplyKeyboardRemove -> [replyKeyboardHide](https://core.telegram.org/constructor/replyKeyboardHide)

ForceReply -> [replyKeyboardForceReply](https://core.telegram.org/constructor/replyKeyboardForceReply)

InlineKeyboardMarkup -> [replyInlineMarkup](https://core.telegram.org/constructor/replyInlineMarkup)

[replyKeyboardMarkup](https://core.telegram.org/constructor/replyKeyboardMarkup)

-----------------------------

example for replyKeyboardMarkup:

OLD:
``` javascript
{
  keyboard: KeyboardButton[][];
  is_persistent?: boolean;
  resize_keyboard?: boolean;
  one_time_keyboard?: boolean;
  input_field_placeholder?: string;
}
```

CURRENT: 
``` javascript
{
  rows: KeyboardButton[];
  persistent?: boolean;
  resize?: boolean;
  single_use?: boolean;
  placeholder?: boolean;
}
```

I tried to make pull request, but permission is denied :)

**Comment by KnorpelSenf** [comment]
1. You are looking at the wrong docs. Check out https://core.telegram.org/bots/api.
2. The docs in this repo are a few versions behind. Reply markup is unaffected, but other types may need to be updated.
3. Everyone has permission to open pull requests. You just need to fork the repo, you cannot directly commit to my tree.
